name: GitHub Actions Demo

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: self-hosted

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Current Directory
        run: pwd

      - name: List Files
        run: ls -la

      - name: Print Date
        run: date

      - name: Display HTML
        run: cat index.html
