name: Deploy Website

on: workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v4

      - name: Copy files
        run: |
          sudo cp index.html /var/www/html/index.html
          
      - name: Print Message
        run: echo "Workflow triggered manually!"
        
